services:
  solario:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=solario;Username=solario;Password=solario
    depends_on:
      - postgres
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: solario
      POSTGRES_USER: solario
      POSTGRES_PASSWORD: solario
    ports:
      - "5432:5432"
    volumes:
      - solario_pg:/var/lib/postgresql/data

volumes:
  solario_pg:
